/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pastry.project;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yvette Rimas
 */
public class CakesItems extends javax.swing.JInternalFrame {

    /**
     * Creates new form CakesItems
     */
    public CakesItems() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CakesItems = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ChocoGanacheLag = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        ChocoSmoresLag = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        ChocoCaramelLag = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        ChocoGanacheReg = new javax.swing.JButton();
        ChocoSmoresReg = new javax.swing.JButton();
        ChocoCaramelReg = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        CakesItems.setBackground(new java.awt.Color(255, 204, 153));
        CakesItems.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(204, 102, 0));
        jLabel11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel11.setText("Slice cake and Cheesecake");
        CakesItems.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));

        ChocoGanacheLag.setText("Chocolate Ganache Cake - L");
        CakesItems.add(ChocoGanacheLag, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 40));

        jButton8.setText("Chocolate Ganache Cake");
        CakesItems.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, 40));

        jButton9.setText("Chocolate Smores Cake");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        CakesItems.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, 40));

        ChocoSmoresLag.setText("Chocolate Smores Cake - L");
        CakesItems.add(ChocoSmoresLag, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, 40));

        jButton11.setText("Chocolate Caramel Cake");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        CakesItems.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, -1, 40));

        ChocoCaramelLag.setText("Chocolate Caramel Cake - L");
        CakesItems.add(ChocoCaramelLag, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, 40));

        jButton13.setText("Chocolate Oreo Cake");
        CakesItems.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, -1, 40));

        jButton14.setText("Chocolate Oreo Cake - L");
        CakesItems.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 40));

        jButton15.setText("Tiramisu Cake");
        CakesItems.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, -1, 40));

        jButton16.setText("Tiramisu Cake - L");
        CakesItems.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, 40));

        jButton17.setText("Red Velvet Cake");
        CakesItems.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, -1, 40));

        jButton18.setText("Red Velvet Cake - L");
        CakesItems.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, 40));

        jButton19.setText("Carrot Cake");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        CakesItems.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, -1, 40));

        jButton20.setText("Strawberry Pistachio Cake");
        CakesItems.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, -1, 40));

        jButton21.setText("Blueberry Cheesecake");
        CakesItems.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 640, -1, 40));

        jButton22.setText("Carrot Cake - L");
        CakesItems.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, 40));

        jButton23.setText("Strawberry Pistachio Cake - L");
        CakesItems.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, 40));

        jButton24.setText("Blueberry Cheesecake - L");
        CakesItems.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, 40));

        jButton25.setText("Chocolate Mousse");
        CakesItems.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 690, -1, 40));

        jButton26.setText("Chocolate Mousse - L");
        CakesItems.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, 40));

        jLabel12.setBackground(new java.awt.Color(204, 102, 0));
        jLabel12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel12.setText("Wholecake and Cheesecake");
        CakesItems.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        ChocoGanacheReg.setText("Chocolate Ganache Cake - R");
        ChocoGanacheReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChocoGanacheRegActionPerformed(evt);
            }
        });
        CakesItems.add(ChocoGanacheReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 40));

        ChocoSmoresReg.setText("Chocolate Smores Cake - R");
        CakesItems.add(ChocoSmoresReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, 40));

        ChocoCaramelReg.setText("Chocolate Caramel Cake - R");
        CakesItems.add(ChocoCaramelReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, 40));

        jButton30.setText("Chocolate Oreo Cake - R");
        CakesItems.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 40));

        jButton31.setText("Tiramisu Cake - R");
        CakesItems.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, 40));

        jButton32.setText("Red Velvet Cake - R");
        CakesItems.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, 40));

        jButton33.setText("Carrot Cake - R");
        CakesItems.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, 40));

        jButton34.setText("Strawberry Pistachio Cake - R");
        CakesItems.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, 40));

        jButton35.setText("Blueberry Cheesecake - R");
        CakesItems.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, 40));

        jButton36.setText("Chocolate Mousse - R");
        CakesItems.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CakesItems, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CakesItems, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void ChocoGanacheRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChocoGanacheRegActionPerformed


    }//GEN-LAST:event_ChocoGanacheRegActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CakesItems;
    private javax.swing.JButton ChocoCaramelLag;
    private javax.swing.JButton ChocoCaramelReg;
    private javax.swing.JButton ChocoGanacheLag;
    private javax.swing.JButton ChocoGanacheReg;
    private javax.swing.JButton ChocoSmoresLag;
    private javax.swing.JButton ChocoSmoresReg;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    // End of variables declaration//GEN-END:variables
}
