/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pastry.project;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Yvette Rimas
 */
public class DrinksItems extends javax.swing.JInternalFrame {

    /**
     * Creates new form CakesItems
     */
    public DrinksItems() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DrinksItems = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        DrinksItems.setBackground(new java.awt.Color(255, 204, 153));
        DrinksItems.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton27.setText("Lemon Iced Tea");
        DrinksItems.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 160, 40));

        jButton28.setText("Cucumber");
        DrinksItems.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 160, 40));

        jButton29.setText("Blue Lemonade");
        DrinksItems.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 160, 40));

        jButton30.setText("Lychee");
        DrinksItems.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 160, 40));

        jButton31.setText("Sola");
        DrinksItems.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 160, 40));

        jButton32.setText("Root Beer");
        DrinksItems.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 160, 40));

        jButton33.setText("Canada Dry");
        DrinksItems.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 160, 40));

        jButton34.setText("Bottled Water");
        DrinksItems.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 160, 40));

        jButton35.setText("Soda");
        DrinksItems.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 160, 40));

        jButton36.setText("Fresh Milk");
        DrinksItems.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DrinksItems, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DrinksItems, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DrinksItems;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    // End of variables declaration//GEN-END:variables
}
