/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pastry.project;

import javax.swing.DefaultListModel;



/**
 *
 * @author Yvette Rimas
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        items = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DrinksList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        right = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        OrderName = new javax.swing.JTextField();
        Quantity = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        Subtotal = new javax.swing.JTextField();
        Add2Cart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cart = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Add2Cart1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left.setBackground(new java.awt.Color(255, 255, 255));
        left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        items.setBackground(new java.awt.Color(204, 102, 0));
        items.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(102, 51, 0));
        jLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel18.setText("Others");
        items.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 60, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "With Beverage", "A la Carte", "Combo Meal", " ", " ", " " }));
        items.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 170, -1));

        jLabel19.setBackground(new java.awt.Color(102, 51, 0));
        jLabel19.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel19.setText("Cakes and Cheesecakes");
        items.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 40));

        jLabel20.setBackground(new java.awt.Color(102, 51, 0));
        jLabel20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel20.setText("Rice Meals");
        items.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 100, 40));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yogurt Smoothies", "Fruit Ades", " ", " ", " " }));
        items.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 180, -1));

        jLabel21.setBackground(new java.awt.Color(102, 51, 0));
        jLabel21.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel21.setText("With Beverage");
        items.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 90, 20));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "With Beverage", "A la Carte", "Combo Meal", " ", " ", " " }));
        items.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 170, -1));

        jLabel22.setBackground(new java.awt.Color(102, 51, 0));
        jLabel22.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel22.setText("Pasta");
        items.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, 60, 20));

        jLabel23.setBackground(new java.awt.Color(102, 51, 0));
        jLabel23.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel23.setText("Pizza");
        items.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 60, 20));

        jLabel25.setBackground(new java.awt.Color(102, 51, 0));
        jLabel25.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel25.setText("Combo Meal Choices");
        items.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 130, 20));

        jLabel26.setBackground(new java.awt.Color(102, 51, 0));
        jLabel26.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel26.setText("With Slice of Cake");
        items.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 130, 20));

        jLabel27.setBackground(new java.awt.Color(102, 51, 0));
        jLabel27.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel27.setText("NonCoffee Items");
        items.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 130, 20));

        jLabel28.setBackground(new java.awt.Color(102, 51, 0));
        jLabel28.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel28.setText("Coffee Items");
        items.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 130, 20));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espresso - Hot", "Espresso - Cold", "Frappuccino - Cream", "Frappuccino - Espresso", " ", " ", " " }));
        items.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 180, -1));

        jLabel24.setBackground(new java.awt.Color(102, 51, 0));
        jLabel24.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel24.setText("Drinks");
        items.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 60, 20));

        jLabel29.setBackground(new java.awt.Color(102, 51, 0));
        jLabel29.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel29.setText("Fresh Fruit Shakes");
        items.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 140, 20));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item"
            }
        ));
        jScrollPane14.setViewportView(jTable2);

        items.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 190, 150));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item"
            }
        ));
        jScrollPane16.setViewportView(jTable4);

        items.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 180, 150));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item"
            }
        ));
        jScrollPane17.setViewportView(jTable5);

        items.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 180, 150));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item"
            }
        ));
        jScrollPane18.setViewportView(jTable6);

        items.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 180, 190));

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item"
            }
        ));
        jScrollPane19.setViewportView(jTable7);

        items.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 180, 190));

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item"
            }
        ));
        jScrollPane20.setViewportView(jTable8);

        items.add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 170, 150));

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item"
            }
        ));
        jScrollPane21.setViewportView(jTable9);

        items.add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 180, 150));

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item"
            }
        ));
        jScrollPane22.setViewportView(jTable10);

        items.add(jScrollPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 180, 150));

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item"
            }
        ));
        jScrollPane23.setViewportView(jTable11);

        items.add(jScrollPane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 170, 150));

        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item"
            }
        ));
        jScrollPane24.setViewportView(jTable12);

        items.add(jScrollPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, 170, 150));

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setText("Slice");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        items.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton2.setText("Whole");
        items.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        DrinksList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lemon Iced Tea", "Cucumber", "Blue Lemonade", "Lychee", "Sola", "Root Beer", "Canada Dry", "Fresh Milk", "Soda", "Bottled Water" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        DrinksList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DrinksListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(DrinksList);

        items.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 210, 170));

        left.add(items, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 1000, 750));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("MENU");
        left.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo 2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        left.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 80, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pngtree-vector-house-icon-png-image_695726.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        left.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        container.add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 865));

        right.setBackground(new java.awt.Color(102, 51, 0));
        right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        right.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 20, 25));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 153));
        jLabel11.setText("Subtotal");
        right.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));
        right.add(OrderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 30));
        right.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 100, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 153));
        jLabel16.setText("Quantity");
        right.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));
        right.add(Subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 50, 130, 30));

        Add2Cart.setText("Clear");
        Add2Cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add2CartActionPerformed(evt);
            }
        });
        right.add(Add2Cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 140, 30));

        Cart.setBackground(new java.awt.Color(255, 204, 153));
        Cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Price", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Cart);

        right.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 55)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 204, 153));
        jLabel17.setText("--");
        right.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jButton2.setText("Print");
        right.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 810, 140, 40));

        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        right.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 810, 140, 40));

        jLabel30.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 55)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 204, 153));
        jLabel30.setText("Your Order#");
        right.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 204, 153));
        jLabel31.setText("Order name");
        right.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        Add2Cart1.setText("Add to Cart");
        Add2Cart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add2Cart1ActionPerformed(evt);
            }
        });
        right.add(Add2Cart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 140, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 204, 153));
        jLabel12.setText("Price");
        right.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));
        right.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 110, 30));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 204, 153));
        jLabel32.setText("Pay:");
        right.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 700, -1, -1));
        right.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 700, 110, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 204, 153));
        jLabel33.setText("Total:");
        right.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 700, -1, -1));
        right.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 700, 110, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 204, 153));
        jLabel34.setText("Change:");
        right.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 740, -1, -1));
        right.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 740, 110, -1));

        container.add(right, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 540, 865));

        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Home_OrderPastry home = new Home_OrderPastry();
        home.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void Add2Cart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add2Cart1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add2Cart1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Add2CartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add2CartActionPerformed

    }//GEN-LAST:event_Add2CartActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked
    DefaultListModel m = DefaultListmodel();
    private void DrinksListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrinksListMouseClicked
        String data = DrinksList.getSelectedValue().toString();
        
        m.addElement (data);
        
        OrderName.setText(m);
    }//GEN-LAST:event_DrinksListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add2Cart;
    private javax.swing.JButton Add2Cart1;
    private javax.swing.JTable Cart;
    private javax.swing.JList<String> DrinksList;
    private javax.swing.JTextField OrderName;
    private javax.swing.JTextField Price;
    private javax.swing.JSpinner Quantity;
    private javax.swing.JTextField Subtotal;
    private javax.swing.JPanel container;
    private javax.swing.JPanel items;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel left;
    private javax.swing.JPanel right;
    // End of variables declaration//GEN-END:variables

    private DefaultListModel DefaultListmodel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
