/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pastry.project;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Yvette Rimas
 */
public class NonCoffeeItems extends javax.swing.JInternalFrame {

    /**
     * Creates new form CakesItems
     */
    public NonCoffeeItems() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NonCoffeeItems = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        NonCoffeeItems.setBackground(new java.awt.Color(255, 204, 153));
        NonCoffeeItems.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(204, 102, 0));
        jLabel11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel11.setText("Fruit Ades");
        NonCoffeeItems.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        jButton7.setText("Raspberry Yogurt Smoothie");
        NonCoffeeItems.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 180, 40));

        jButton8.setText("Blueberry Ade");
        NonCoffeeItems.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 180, 40));

        jButton9.setText("Raspberry Ade");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        NonCoffeeItems.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 180, 40));

        jButton10.setText("Plain Yogurt Smoothie");
        NonCoffeeItems.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 180, 40));

        jButton11.setText("Mango Ade");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        NonCoffeeItems.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 180, 40));

        jButton13.setText("Strawberry Ade");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        NonCoffeeItems.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 180, 40));

        jButton15.setText("Green Apple Ade");
        NonCoffeeItems.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 180, 40));

        jLabel12.setBackground(new java.awt.Color(204, 102, 0));
        jLabel12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel12.setText("Yogurt Smoothies");
        NonCoffeeItems.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jButton27.setText("Strawberry Yogurt Smoothie");
        NonCoffeeItems.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 180, 40));

        jButton28.setText("Mango Yogurt Smoothie");
        NonCoffeeItems.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 180, 40));

        jButton29.setText("Blueberry Yogurt Smoothie");
        NonCoffeeItems.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NonCoffeeItems, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NonCoffeeItems, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NonCoffeeItems;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    // End of variables declaration//GEN-END:variables
}
