/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pastry.project;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Yvette Rimas
 */
public class OthersItems extends javax.swing.JInternalFrame {

    /**
     * Creates new form CakesItems
     */
    public OthersItems() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OthersItems = new javax.swing.JPanel();
        MojosOrig = new javax.swing.JButton();
        PotatoBalls = new javax.swing.JButton();
        ChickenNuggets = new javax.swing.JButton();
        FrenchFries = new javax.swing.JButton();
        SavoryFries = new javax.swing.JButton();
        MozarellaSticks = new javax.swing.JButton();
        MojosHot = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        OthersItems.setBackground(new java.awt.Color(255, 204, 153));
        OthersItems.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MojosOrig.setText("Mojos Original");
        MojosOrig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MojosOrigActionPerformed(evt);
            }
        });
        OthersItems.add(MojosOrig, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 160, 40));

        PotatoBalls.setText("Potato Balls");
        PotatoBalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PotatoBallsActionPerformed(evt);
            }
        });
        OthersItems.add(PotatoBalls, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 160, 40));

        ChickenNuggets.setText("Chicken Nuggets");
        ChickenNuggets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenNuggetsActionPerformed(evt);
            }
        });
        OthersItems.add(ChickenNuggets, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 160, 40));

        FrenchFries.setText("French Fries");
        FrenchFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrenchFriesActionPerformed(evt);
            }
        });
        OthersItems.add(FrenchFries, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 160, 40));

        SavoryFries.setText("Savory Fries");
        SavoryFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavoryFriesActionPerformed(evt);
            }
        });
        OthersItems.add(SavoryFries, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 160, 40));

        MozarellaSticks.setText("Mozarella Sticks");
        MozarellaSticks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MozarellaSticksActionPerformed(evt);
            }
        });
        OthersItems.add(MozarellaSticks, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 160, 40));

        MojosHot.setText("Mojos Hot");
        MojosHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MojosHotActionPerformed(evt);
            }
        });
        OthersItems.add(MojosHot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(OthersItems, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OthersItems, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PotatoBallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PotatoBallsActionPerformed
        double PriceofItem = 60.00;
        String NameofItem = "Potato Balls";
        
        Menu.OrderName.setText(NameofItem);
        Menu.Price.setText(Double.toString(PriceofItem));
    }//GEN-LAST:event_PotatoBallsActionPerformed

    private void MozarellaSticksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MozarellaSticksActionPerformed
        double PriceofItem = 60.00;
        String NameofItem = "Mozarella Sticks";
        
        Menu.OrderName.setText(NameofItem);
        Menu.Price.setText(Double.toString(PriceofItem));
    }//GEN-LAST:event_MozarellaSticksActionPerformed

    private void ChickenNuggetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenNuggetsActionPerformed
        double PriceofItem = 60.00;
        String NameofItem = "Chicken Nuggets";
        
        Menu.OrderName.setText(NameofItem);
        Menu.Price.setText(Double.toString(PriceofItem));
    }//GEN-LAST:event_ChickenNuggetsActionPerformed

    private void FrenchFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrenchFriesActionPerformed
        double PriceofItem = 60.00;
        String NameofItem = "French Fries";
        
        Menu.OrderName.setText(NameofItem);
        Menu.Price.setText(Double.toString(PriceofItem));
    }//GEN-LAST:event_FrenchFriesActionPerformed

    private void SavoryFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavoryFriesActionPerformed
        double PriceofItem = 60.00;
        String NameofItem = "Savory Fries";
        
        Menu.OrderName.setText(NameofItem);
        Menu.Price.setText(Double.toString(PriceofItem));
    }//GEN-LAST:event_SavoryFriesActionPerformed

    private void MojosHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MojosHotActionPerformed
        double PriceofItem = 60.00;
        String NameofItem = "Mojos Hot";
        
        Menu.OrderName.setText(NameofItem);
        Menu.Price.setText(Double.toString(PriceofItem));
    }//GEN-LAST:event_MojosHotActionPerformed

    private void MojosOrigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MojosOrigActionPerformed
        double PriceofItem = 60.00;
        String NameofItem = "Mojos Original";
        
        Menu.OrderName.setText(NameofItem);
        Menu.Price.setText(Double.toString(PriceofItem));
    }//GEN-LAST:event_MojosOrigActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChickenNuggets;
    private javax.swing.JButton FrenchFries;
    private javax.swing.JButton MojosHot;
    private javax.swing.JButton MojosOrig;
    private javax.swing.JButton MozarellaSticks;
    private javax.swing.JPanel OthersItems;
    private javax.swing.JButton PotatoBalls;
    private javax.swing.JButton SavoryFries;
    // End of variables declaration//GEN-END:variables
}
