/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pastry.project;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Yvette Rimas
 */
public class PastaItems extends javax.swing.JInternalFrame {

    /**
     * Creates new form CakesItems
     */
    public PastaItems() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PastaItems = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        PastaItems.setBackground(new java.awt.Color(255, 204, 153));
        PastaItems.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(204, 102, 0));
        jLabel11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel11.setText("A la Carte");
        PastaItems.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        jButton8.setText("Chicken Pasta");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        PastaItems.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 160, 40));

        jButton11.setText("Baked Mac");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        PastaItems.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 160, 40));

        jButton13.setText("Tinapa Pasta");
        PastaItems.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 160, 40));

        jButton15.setText("Beef Spaghetti");
        PastaItems.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 160, 40));

        jButton17.setText("Garlic Bread");
        PastaItems.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 630, 160, 40));

        jLabel12.setBackground(new java.awt.Color(204, 102, 0));
        jLabel12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel12.setText("Pasta with Beverage");
        PastaItems.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chicken Pasta", "Tuna Pasta", "Baked Mac", "Tinapa Pasta", "Beef Spaghetti", " " }));
        PastaItems.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 230, 40));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lemon Iced Tea", "Cucumber", "Blue Lemonade", "Lychee" }));
        PastaItems.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 230, 40));

        jButton1.setText("Add");
        PastaItems.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        jButton2.setText("Tuna Pasta");
        PastaItems.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PastaItems, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PastaItems, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PastaItems;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    // End of variables declaration//GEN-END:variables
}
