/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pastry.project;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Yvette Rimas
 */
public class PizzaItems extends javax.swing.JInternalFrame {

    /**
     * Creates new form CakesItems
     */
    public PizzaItems() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PizzaItems = new javax.swing.JPanel();
        Breakfast = new javax.swing.JButton();
        Hawaiian = new javax.swing.JButton();
        Pepperoni = new javax.swing.JButton();
        Veggie = new javax.swing.JButton();
        Cheese = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        PizzaItems.setBackground(new java.awt.Color(255, 204, 153));
        PizzaItems.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Breakfast.setText("Breakfast Pizza");
        Breakfast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BreakfastActionPerformed(evt);
            }
        });
        PizzaItems.add(Breakfast, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 160, 40));

        Hawaiian.setText("Hawaiian Pizza");
        Hawaiian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HawaiianActionPerformed(evt);
            }
        });
        PizzaItems.add(Hawaiian, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 160, 40));

        Pepperoni.setText("Pepperoni Pizza");
        Pepperoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PepperoniActionPerformed(evt);
            }
        });
        PizzaItems.add(Pepperoni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 160, 40));

        Veggie.setText("Veggie Pizza");
        Veggie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeggieActionPerformed(evt);
            }
        });
        PizzaItems.add(Veggie, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 160, 40));

        Cheese.setText("Cheese Pizza");
        Cheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheeseActionPerformed(evt);
            }
        });
        PizzaItems.add(Cheese, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PizzaItems, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PizzaItems, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PepperoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PepperoniActionPerformed
        double PriceofItem = 400.00;
        String NameofItem = "Pepperoni Pizza";
        
        Menu.OrderName.setText(NameofItem);
        Menu.Price.setText(Double.toString(PriceofItem));
    }//GEN-LAST:event_PepperoniActionPerformed

    private void VeggieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeggieActionPerformed
        double PriceofItem = 390.00;
        String NameofItem = "Veggie Pizza";
        
        Menu.OrderName.setText(NameofItem);
        Menu.Price.setText(Double.toString(PriceofItem));
    }//GEN-LAST:event_VeggieActionPerformed

    private void CheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheeseActionPerformed
        double PriceofItem = 390.00;
        String NameofItem = "Cheese Pizza";
        
        Menu.OrderName.setText(NameofItem);
        Menu.Price.setText(Double.toString(PriceofItem));
    }//GEN-LAST:event_CheeseActionPerformed

    private void BreakfastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BreakfastActionPerformed
        double PriceofItem = 410.00;
        String NameofItem = "Breakfast Pizza";
        
        Menu.OrderName.setText(NameofItem);
        Menu.Price.setText(Double.toString(PriceofItem));
    }//GEN-LAST:event_BreakfastActionPerformed

    private void HawaiianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HawaiianActionPerformed
        double PriceofItem = 400.00;
        String NameofItem = "Hawaiian Pizza";
        
        Menu.OrderName.setText(NameofItem);
        Menu.Price.setText(Double.toString(PriceofItem));
    }//GEN-LAST:event_HawaiianActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Breakfast;
    private javax.swing.JButton Cheese;
    private javax.swing.JButton Hawaiian;
    private javax.swing.JButton Pepperoni;
    private javax.swing.JPanel PizzaItems;
    private javax.swing.JButton Veggie;
    // End of variables declaration//GEN-END:variables
}
