/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pastry.project;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Yvette Rimas
 */
public class PizzaItems extends javax.swing.JInternalFrame {

    /**
     * Creates new form CakesItems
     */
    public PizzaItems() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PizzaItems = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        PizzaItems.setBackground(new java.awt.Color(255, 204, 153));
        PizzaItems.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setText("Breakfast Pizza");
        PizzaItems.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 160, 40));

        jButton10.setText("Hawaiian Pizza");
        PizzaItems.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 160, 40));

        jButton27.setText("Pepperoni Pizza");
        PizzaItems.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 160, 40));

        jButton28.setText("Veggie Pizza");
        PizzaItems.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 160, 40));

        jButton29.setText("Cheese Pizza");
        PizzaItems.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PizzaItems, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PizzaItems, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PizzaItems;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
